apiVersion: apps/v1
kind: Deployment
metadata:
  name: microhub-posts
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microhub-posts
  template:
    metadata:
      labels:
        app: microhub-posts
    spec:
      containers:
        - name: microhub-posts
          image: microhubacr.azurecr.io/microhub-posts:7.0
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@microhub-postgres.ingress.svc.cluster.local:5432/microservices
            - name: USERS_SERVICE_URL
              value: http://9.235.155.69
---
apiVersion: v1
kind: Service
metadata:
  name: microhub-posts-service
  namespace: ingress
  labels:
    app: microhub-posts
spec:
  type: ClusterIP
  selector:
    app: microhub-posts
  ports:
    - name: http
      port: 8080
      targetPort: 8080
