apiVersion: apps/v1
kind: Deployment
metadata:
  name: microhub-profile
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microhub-profile
  template:
    metadata:
      labels:
        app: microhub-profile
    spec:
      containers:
        - name: microhub-profile
          image: microhubacr.azurecr.io/microhub-profile:7.0
          ports:
            - containerPort: 3004
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@microhub-postgres.ingress.svc.cluster.local:5432/microservices
            - name: USERS_SERVICE_URL
              value: http://9.235.155.69
            - name: POSTS_SERVICE_URL
              value: http://9.235.155.69
            - name: LIKES_SERVICE_URL
              value: http://9.235.155.69
            - name: COMMENTS_SERVICE_URL
              value: http://9.235.155.69
---
apiVersion: v1
kind: Service
metadata:
  name: microhub-profile-service
  namespace: ingress
  labels:
    app: microhub-profile
spec:
  type: ClusterIP
  selector:
    app: microhub-profile
  ports:
    - name: http
      port: 3004
      targetPort: 3004
